version: "3"

services:
  server:
    build: ../
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD=wowverysecret
      - DB_USER=admin
      - DB_name=db
      - DB_HOST=postgres

  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=wowverysecret
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 55008:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  db-data:
